<Project Sdk="Microsoft.NET.Sdk">

	<!-- Ensure settings files are compiled so their types are available to the project -->

	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.SqlServer" />
		<PackageReference Include="MailKit" />
		<PackageReference Include="MassTransit" />
		<PackageReference Include="MassTransit.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.AspNetCore.Authorization" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
        <PackageReference Include="Microsoft.AspNetCore.WebUtilities" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
		<PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Sinks.Seq" />
        <PackageReference Include="Stripe.net" />
        <PackageReference Include="QuestPDF" />
    </ItemGroup>
    
	<ItemGroup>
		<ProjectReference Include="..\MechanicShop.Application\MechanicShop.Application.csproj" />
	</ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    </ItemGroup>


    <ItemGroup>
        <None Update="Templates\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
