<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<ProjectReference Include="..\MechanicShop.Domain\MechanicShop.Domain.csproj" />
	</ItemGroup>
	<ItemGroup> 
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" /> 
		<PackageReference Include="MassTransit" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
        <PackageReference Include="MediatR" />
    </ItemGroup>
</Project>
